### ISSUE TITLE
Loading Bar doesn't show

### ISSUE THREAD

**Issue by dhardtke** [aitboudad/ng-loading-bar#10]
Hey,

thanks for your package.

Unfortunately, it doesn't work in our proejct.

I dug into the code and I cannot find out why. It seems `progress.started` is never true. Also I found that the `_pendingRequests` counter gets emitted as `0` and then, afterwards, the `LoadingBarComponent` subscribes to the `http.pending` event. Why is that? Might this be the cause of the problem?

We are using a multi-module setup with one module that acts as a root module (`AppModule`) and a `SharedModule` that each module imports.

Overall, this is very frustrating since there is absolutely no package doing what your package does.

**Comment by aitboudad** [comment]
Hi,
`ng-loading-bar` is tightly coupled to `Http` service so make sure that `NgLoadingBarHttp` is used see #6,
also `NgLoadingBarModule` should be imported in your root module `NgLoadingBarModule.forRoot()`

**Note**: I'm planning to improve this lib to be more clean and customizable in the near future

**Comment by dhardtke** [comment]
Thanks for your quick reply.

I am using your package in conjunction with ng2-translate and I can see that the LoadingBarComponent subscribes to the Subject *after* the first request was made by ng2-translate's StaticTranslateLoader.

I guess I'll have to find another way to show a loading bar when HTTP requests are in progress.
