### ISSUE TITLE
Disable the loading bar for certain HTTP requests

### ISSUE THREAD

**Issue by rwngallego** [aitboudad/ng-loading-bar#11]
The package angular-loading-bar which is similar but for Angular 1.x has an option that can be injected into the $http request options that allow us to turn off the loading bar, does it support it? If not, it would be nice and useful to have it :)

```
this.$http
      .get(`${config.API_URL}${url}`, {
        ignoreLoadingBar: true,
      }).then(() => {
```

**Comment by aitboudad** [comment]
yes, see https://github.com/aitboudad/ng-loading-bar/blob/master/src/loading-bar.http.ts#L9

**Comment by rwngallego** [comment]
That's perfect. You rock!
