### ISSUE TITLE
Modules with lazy loading.

### ISSUE THREAD

**Issue by Tolitech** [aitboudad/ng-loading-bar#14]
Hello.
In my project I have multiple modules with lazy loading, however, the component only displays the "progress indicator" when the services are part of the root module.

While in another module, the "progress bar" is never displayed.
It only appears in other modules when I put the tag on every page html.

That is, putting the tag in the app.component.html only works for some services, being that for services created in the modules, I have to put in all the html pages.

Is there any way to get around this and just keep the tag in app.component.html?

thank you.

**Comment by chihab** [comment]
@Tolitech could you please provide a plunker reproducing the issue ?

**Comment by Tolitech** [comment]
Hello.
I created a very simple structure with root, shared, account...

In this small example, you can identify that the component only appears in the app.component and does not run on the other modules.

Note that the loading-bar-spinner div tag is always display: none with lazy loading modules.

Please export the project and run it locally.
Online is not running (there should be limitations in the online editor).

https://stackblitz.com/edit/angular-vkynnc


![sample](https://user-images.githubusercontent.com/20425889/28999221-03a05dae-7a15-11e7-81a0-45963897b903.png)

**Comment by aitboudad** [comment]
Thanks for the link, to fix you issue just ensure that `NgLoadingBarModule` and `HttpModule` is only part of root module.

```ts
export class SharedModule {
  static forRoot(): any {
    return [
      { ngModule: SharedModule },
      HttpModule,
      NgLoadingBarModule.forRoot(),
    ];
  }
}
```

**Comment by chihab** [comment]
Yes indeed.

Here is the shared module you should have.

```javascript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { NgLoadingBarModule } from 'ng-loading-bar';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule
  ]
})
export class SharedModule {
  static forRoot() {
    return [
      {ngModule: SharedModule},
      HttpModule,
      NgLoadingBarModule.forRoot(),
    ];
  }
}
```

Details:

If HttpModule or NgLoadingBarModule are in the exports or providers list in the shared module, a new corresponding instance would be provided by the child injector. The loading bar component wouldn't know about the new instance's 'pending' subject as it has only subscribed to the one provided by the root injector.

**Comment by Spanja** [comment]
Hello,
I get a similar issue with the new alpha 3 :

If I access my app with the root URL and then navigate to a lazy loaded module, the loading bar is well displayed on each HttpClient call.
But if I then refresh my app being in my lazy loaded module (I press F5), I can't see the bar anymore.
It seems that the bar is well displayed only if I load app with the root URL.

Here is my shared module :

export class SharedModule {
  static forRoot() {
    return [
      { ngModule: SharedModule },
      HttpClientModule,
      LoadingBarHttpClientModule,
    ];
  }
}

**Comment by Tolitech** [comment]
@Spanja 
The only way I was able to work with various lazy-loading modules and sharing modules was to put the HttpModule and ngx-loading-bar into the app.module.ts

Remove all references, imports, exports and declarations from anywhere, including the Shared Module.
Just leave it in the app.module that will work correctly.

**Comment by Spanja** [comment]
I get same results with declaring LoadingBarHttpClientModule only in app module.

I'm using the new HttpClientModule instead of HttpModule

**Comment by Tolitech** [comment]
@Spanja 

Sorry for the misunderstanding.
I have tested here and my code happens the same problem that you are facing.

A refresh by a route other than the main one, the loading-bar no longer appears.

Unfortunately I can not help you, just confirm that it is a possible bug in the component.

I think you should open a new issue for the creator.

**Comment by jayzyaj** [comment]
I'm having the same thing with @Spanja is the issue fixed?
