### ISSUE TITLE
Adding a new service to manage loading/progress bar manually

### ISSUE THREAD

**Issue by bhaskerchari** [aitboudad/ng-loading-bar#4]
I think we also need a service which handles showing loading/progress bar manually in some other common use cases too which are asynchronous in nature but may not necessarily be the XHR requests which is what this project is currently aimed at to provide a solution for.

I think it wouldn't be a complete solution until we have a full control on showing and hiding a loading bar even manually in some usecases such as using setTimeOuts, reading data from the offline browser storage, page transitions etc;

Thanks,
Bhasker

**Comment by aitboudad** [comment]
you can now use `LoadingBarService` to manage loading bar manually,
see https://github.com/aitboudad/ng-loading-bar/blob/master/demo/app/app.ts#L42
