### ISSUE TITLE
Does not seem to fire when http request made....

### ISSUE THREAD

**Issue by ganySA** [aitboudad/ng-loading-bar#6]
the component renders in the html dom i can see it if i open the html, however when http requests are running it does not go from display:none to visible. I assume it is not firing or picking up http.

Could this be because i am using my own Http Interceptor (i am using token authentication and need to have my own interceptor)

In my app module i am doing:

```
 providers: [
    {

      provide: Http,
      useFactory: httpFactory, //(xhrBackend: XHRBackend, requestOptions: RequestOptions, appSettings: AppSettings, nav) => new HttpInterceptor(xhrBackend, requestOptions, appSettings, nav),
      deps: [XHRBackend, RequestOptions, AppSettings],

    },
```
And 

```
export function httpFactory(xhrBackend: XHRBackend, requestOptions: RequestOptions, appSettings: AppSettings) {
  return new HttpInterceptor(xhrBackend, requestOptions, appSettings);
}
```

With HttpInterceptor being my own interceptor.... is this somehow messing with your code?

**Comment by aitboudad** [comment]
in that case you should extend `NgLoadingBarHttp`

```ts
export class HttpInterceptor extends NgLoadingBarHttp {
    ...
}
```
